### PR TITLE
Merge tests into one file

### PR DESCRIPTION
**Pull request by nikhil-zinjurde-imgtec**
Check openwrt version and device info are pretty simpler type of tests and hence seems only logical to keep them in one file. Also, re-arranged the tests to run device info test in the initial set.

### CODE REVIEW

**Review by abhijit-mahajani-imgtec — COMMENTED** [review]
commit message could be updated to cover the
movement of device info into openwrt_version test.
filename can also renamed to openwrt_version_info or something which explains both the tests.

**Comment by Ham22** [comment]
Why was this done? Reading the commit messages should answer my quesiton

**Comment by nikhil-zinjurde-imgtec** [comment]
The description in the pull request should answer your question.  Wouldn't the commit message become too long for such an simple change?

**Comment by nikhil-zinjurde-imgtec** [comment]
... still I have some description to the commit, it could be opened and read through to understand the reason of doing this. Not always all commit messages can tell you exactly what they do

**Comment by Ham22** [comment]
PR description doesn't get into the history of the repo. No change is too simple for some explanation. Also you have a typo

**Comment by nikhil-zinjurde-imgtec** [comment]
Ok, got it.  Added description to the commit and fixed the typo also

**Review by Ham22 — APPROVED** [review]

**Pull request merged**
